### PR TITLE
add method&&path support fix #6

### LINKED ISSUE #6: Support for method and path combination
Is there a way to exclude specific methods from a path?

For example suppose I have a `/items` path, and want to skip the middleware on `GET /items` and run it on `POST | PUT | DELETE /items`.

Something like:

```js
app.use(myMiddleware.unless({ path: { "/items": [ 'GET' ] } }));
```

### PR DESCRIPTION
**Pull request by zhiyelee**
Fix #6 

Can use like this:

```js
var unless = require('express-unless');


var static = express.static(__dirname + '/public');
static.unless = unless;
var params = {
      path: [
        {
          url: '/test',
          methods: ['POST', 'GET']
        },
        {
          url: '/boo',
          methods: ['POST']
        },
      ]
};
app.use(static.unless({ path: [ ] }));
```

### CODE REVIEW

**Comment by zhiyelee** [comment]
@jfromaniello I will update the README if you want to merge this.

**Comment by jfromaniello** [comment]
looks good to me, can you rebase and update the readme?

**Comment by zhiyelee** [comment]
will do that.

**Comment by zhiyelee** [comment]
hi @jfromaniello  Ready for review. Thank you!

**Comment by jfromaniello** [comment]
Thanks, published as v0.3.0

**Comment by zhiyelee** [comment]
thank you

**Pull request merged**
